// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAae37NwdockHs1VpX8Dqua_BBsl0lUetk',
    appId: '1:757948771348:web:d4161f019b4c6bd38bcb01',
    messagingSenderId: '757948771348',
    projectId: 'parkinson-b5e7a',
    authDomain: 'parkinson-b5e7a.firebaseapp.com',
    storageBucket: 'parkinson-b5e7a.appspot.com',
    measurementId: 'G-X918SY5BQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdU8iZ8baEV82YBSRfNo0DQuyHWyt0BgA',
    appId: '1:757948771348:android:a336e3b2686562128bcb01',
    messagingSenderId: '757948771348',
    projectId: 'parkinson-b5e7a',
    storageBucket: 'parkinson-b5e7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHZJnwPefJbiI8FpyMBmp19H6hdvNDCo8',
    appId: '1:757948771348:ios:c6810488dd3ef3a48bcb01',
    messagingSenderId: '757948771348',
    projectId: 'parkinson-b5e7a',
    storageBucket: 'parkinson-b5e7a.appspot.com',
    iosBundleId: 'com.example.parkinson',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHZJnwPefJbiI8FpyMBmp19H6hdvNDCo8',
    appId: '1:757948771348:ios:1682ccf33785ecaa8bcb01',
    messagingSenderId: '757948771348',
    projectId: 'parkinson-b5e7a',
    storageBucket: 'parkinson-b5e7a.appspot.com',
    iosBundleId: 'com.example.parkinson.RunnerTests',
  );
}
